SET @maxRecordId = (SELECT IFNULL(max(record_id),0) from to_magento_records);

insert into to_magento_records (`record_id`, `identifier`, `type`, `status`)
values (@maxRecordId + 1, 'munt_traian@yahoo.com', 5, 0);

insert into to_magento_datas (`record_id`, `field_name`, `field_value`)
values (@maxRecordId + 1, 'website_id',28),
(@maxRecordId + 1, 'store_id',0),
(@maxRecordId + 1, 'created_in','Admin'),
(@maxRecordId + 1, 'prefix',''),
(@maxRecordId + 1, 'firstname','Traian'),
(@maxRecordId + 1, 'middlename',''),
(@maxRecordId + 1, 'lastname','Munteanu'),
(@maxRecordId + 1, 'suffix',''),
(@maxRecordId + 1, 'email','munt_traian@yahoo.com'),
(@maxRecordId + 1, 'group_id',8),
(@maxRecordId + 1, 'dob',''),
(@maxRecordId + 1, 'password_hash','fhfghfghfghfhg'),
(@maxRecordId + 1, 'default_billing',''),
(@maxRecordId + 1, 'default_shipping',''),
(@maxRecordId + 1, 'taxvat','12345'),
(@maxRecordId + 1, 'confirmation',''),
(@maxRecordId + 1, 'created_at',''),
(@maxRecordId + 1, 'gender',''),
(@maxRecordId + 1, 'rp_token',''),
(@maxRecordId + 1, 'rp_token_created_at',''),
(@maxRecordId + 1, 'disable_auto_group_change',''),
(@maxRecordId + 1, 'c5_custno','11111'),
(@maxRecordId + 1, 'c5_discgrp',''),
(@maxRecordId + 1, 'c5_custcur','EUR'),
(@maxRecordId + 1, 'c5_custdisc',''),
(@maxRecordId + 1, 'c5_custid','111'),
(@maxRecordId + 1, 'is_suspended',''),
(@maxRecordId + 1, 'c5_custbrand',''),
(@maxRecordId + 1, 'c5_omshd',''),
(@maxRecordId + 1, 'c5_omsnv',''),
(@maxRecordId + 1, 'c5_omsmk',''),
(@maxRecordId + 1, 'c5_omskf',''),
(@maxRecordId + 1, 'c5_saldohd',''),
(@maxRecordId + 1, 'c5_saldonv',''),
(@maxRecordId + 1, 'c5_saldomk',''),
(@maxRecordId + 1, 'c5_saldokf',''),
(@maxRecordId + 1, 'c5_mailfkt',''),
(@maxRecordId + 1, 'c5_mailob',''),
(@maxRecordId + 1, 'c5_www',''),
(@maxRecordId + 1, 'c5_gps_long',''),
(@maxRecordId + 1, 'c5_gps_lat',''),
(@maxRecordId + 1, 'c5_shoptype',''),
(@maxRecordId + 1, 'c5_allowed',''),
(@maxRecordId + 1, 'c5_custtypesel',''),
(@maxRecordId + 1, 'mobile_phone','')
;

-- insert biling address
insert into to_magento_datas (`record_id`, `field_name`, `field_value`)
values (@maxRecordId + 1, 'addr_bll_prefix', NULL),
(@maxRecordId + 1, 'addr_bll_firstname', 'Traian'),
(@maxRecordId + 1, 'addr_bll_middlename', NULL),
(@maxRecordId + 1, 'addr_bll_lastname', 'Munteanu'),
(@maxRecordId + 1, 'addr_bll_suffix', NULL),
(@maxRecordId + 1, 'addr_bll_company', 'BrcIT'),
(@maxRecordId + 1, 'addr_bll_street', 'Sos Otenitei 73'),
(@maxRecordId + 1, 'addr_bll_city', 'Bucureti'),
(@maxRecordId + 1, 'addr_bll_country_id', 'RO'),
(@maxRecordId + 1, 'addr_bll_region', NULL),
(@maxRecordId + 1, 'addr_bll_region_id', NULL),
(@maxRecordId + 1, 'addr_bll_postcode', '041299'),
(@maxRecordId + 1, 'addr_bll_telephone', '0722509694'),
(@maxRecordId + 1, 'addr_bll_fax', NULL),
(@maxRecordId + 1, 'addr_bll_vat_id', NULL),
(@maxRecordId + 1, 'addr_bll_vat_is_valid', NULL),
(@maxRecordId + 1, 'addr_bll_vat_request_id', NULL),
(@maxRecordId + 1, 'addr_bll_vat_request_date', NULL),
(@maxRecordId + 1, 'addr_bll_vat_request_success', NULL),
(@maxRecordId + 1, 'addr_bll_mail_to_invoice', NULL),
(@maxRecordId + 1, 'addr_bll_mail_to_homepage', NULL),
(@maxRecordId + 1, 'addr_bll_note', NULL),
(@maxRecordId + 1, 'addr_bll_vat_no', NULL),
(@maxRecordId + 1, 'addr_bll_homepage', NULL),
(@maxRecordId + 1, 'addr_bll_mobile', NULL);

-- insert delivery address
insert into to_magento_datas (`record_id`, `field_name`, `field_value`)
values (@maxRecordId + 1, 'addr_dlv_prefix', NULL),
(@maxRecordId + 1, 'addr_dlv_firstname', 'Traian'),
(@maxRecordId + 1, 'addr_dlv_middlename', NULL),
(@maxRecordId + 1, 'addr_dlv_lastname', 'Munteanu'),
(@maxRecordId + 1, 'addr_dlv_suffix', NULL),
(@maxRecordId + 1, 'addr_dlv_company', 'BrcIT'),
(@maxRecordId + 1, 'addr_dlv_street', 'Sos Otenitei 73'),
(@maxRecordId + 1, 'addr_dlv_city', 'Bucureti'),
(@maxRecordId + 1, 'addr_dlv_country_id', 'RO'),
(@maxRecordId + 1, 'addr_dlv_region', NULL),
(@maxRecordId + 1, 'addr_dlv_region_id', NULL),
(@maxRecordId + 1, 'addr_dlv_postcode', '041299'),
(@maxRecordId + 1, 'addr_dlv_telephone', '0722509694'),
(@maxRecordId + 1, 'addr_dlv_fax', NULL),
(@maxRecordId + 1, 'addr_dlv_vat_id', NULL),
(@maxRecordId + 1, 'addr_dlv_vat_is_valid', NULL),
(@maxRecordId + 1, 'addr_dlv_vat_request_id', NULL),
(@maxRecordId + 1, 'addr_dlv_vat_request_date', NULL),
(@maxRecordId + 1, 'addr_dlv_vat_request_success', NULL),
(@maxRecordId + 1, 'addr_dlv_mail_to_invoice', NULL),
(@maxRecordId + 1, 'addr_dlv_mail_to_homepage', NULL),
(@maxRecordId + 1, 'addr_dlv_note', NULL),
(@maxRecordId + 1, 'addr_dlv_vat_no', NULL),
(@maxRecordId + 1, 'addr_dlv_homepage', NULL),
(@maxRecordId + 1, 'addr_dlv_mobile', NULL);
